### ISSUE TITLE
RuntimeError: cuda runtime error (2) : out of memory

### ISSUE THREAD

**Issue by eyildiz-ugoe** [Microsoft/singleshotpose#12]
So finally I was able to get rid of all pytorch version related problems, and at least I can see the network structure when I execute now. However, for some strange reason I always end up with the specified error.:

```
THCudaCheck FAIL file=/pytorch/torch/lib/THC/generic/THCStorage.cu line=58 error=2 : out of memory
Traceback (most recent call last):
  File "train.py", line 381, in <module>
    model = model.cuda() # model = torch.nn.DataParallel(model, device_ids=[0]).cuda() # Multiple GPU parallelism
  File "/home/user/.local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 216, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/user/.local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 146, in _apply
    module._apply(fn)
  File "/home/user/.local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 146, in _apply
    module._apply(fn)
  File "/home/user/.local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 146, in _apply
    module._apply(fn)
  File "/home/user/.local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 152, in _apply
    param.data = fn(param.data)
  File "/home/user/.local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 216, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "/home/user/.local/lib/python2.7/site-packages/torch/_utils.py", line 69, in _cuda
    return new_type(self.size()).copy_(self, async)
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCStorage.cu:58

```

I've tried various GPUs such as Titan V, 1060ti, 1080ti, no luck.  It can't be the case that I need more than 11 GB memory to run the training session, right? Validation is OK, it runs. Training however, no matter which card I tried, does not run. One should perhaps decrease the batch size? Which config file should one edit then? yolo-pose-pre.cfg or yolo-pose.cfg? Or both? Before I change any of these I wanted to ask if that's actually the reason.

**Comment by hhaAndroid** [comment]
The reason is multithreading，You should modify the worker thread to 0.specifically is 
utils.py:
    options['num_workers'] = '0'

**Comment by eyildiz-ugoe** [comment]
I did that, now it complains about some other file(s) though:

```
2018-07-11 15:44:14 epoch 0, processed 0 samples, lr 0.000100
THCudaCheck FAIL file=/pytorch/torch/lib/THC/generic/THCStorage.cu line=58 error=2 : out of memory
Traceback (most recent call last):
  File "train.py", line 401, in <module>
    niter = train(epoch)
  File "train.py", line 91, in train
    output = model(data)
  File "/home/eren/.local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/eren/workspace/singleshotpose/darknet.py", line 91, in forward
    x = self.models[ind](x)
  File "/home/eren/.local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/eren/.local/lib/python2.7/site-packages/torch/nn/modules/pooling.py", line 143, in forward
    self.return_indices)
  File "/home/eren/.local/lib/python2.7/site-packages/torch/nn/functional.py", line 334, in max_pool2d
    ret = torch._C._nn.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCStorage.cu:58
```

**Comment by hhaAndroid** [comment]
The batch setting should not be greater than 16, otherwise OOM will still appear.

**Comment by eyildiz-ugoe** [comment]
Do you know which config files to edit then? I see already 32 and 64 as batch sizes in config files I could spot now over a minute of looking. Are these the only files?

**Comment by hhaAndroid** [comment]
My gpu is k80,OOM will appear when I set the batch to be greater than 16.so the batch is not set too big，The modified configuration file is: yolo-pose.cfg. Num_worker must be modified

**Comment by eyildiz-ugoe** [comment]
There is no variable called Num_worker in that config file though, I think you confused it with utils.py. 

Nevertheless, here is what one finds in yolo-pose.cfg:

```
[net]
# Testing
batch=32
subdivisions=8
# Training
# batch=64
# subdivisions=8
height=416
width=416
channels=3
momentum=0.9
decay=0.0005
angle=0
saturation = 1.5
exposure = 1.5
hue=.1
```
So I've changed batch there to 8 and 16, and got the following errors, respectively:

```
Traceback (most recent call last):
  File "train.py", line 396, in <module>
    niter = train(epoch)
  File "train.py", line 91, in train
    loss = region_loss(output, target)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/user/workspace/singleshotpose/region_loss.py", line 205, in forward
    pred_corners[0]  = (x0.data + grid_x) / nW
RuntimeError: The size of tensor a (13) must match the size of tensor b (1352) at non-singleton dimension 3
```

```
Traceback (most recent call last):
  File "train.py", line 396, in <module>
    niter = train(epoch)
  File "train.py", line 91, in train
    loss = region_loss(output, target)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/user/workspace/singleshotpose/region_loss.py", line 205, in forward
    pred_corners[0]  = (x0.data + grid_x) / nW
RuntimeError: The size of tensor a (13) must match the size of tensor b (2704) at non-singleton dimension 3
```

**Comment by hhaAndroid** [comment]
first: Num_worker is in utils.py，not in cfg
second:Batch is set in cfg
third：pytorch version must be 0.3，Can't be version 0.4

**Comment by eyildiz-ugoe** [comment]
Okay I got it, works with lower batch_size indeed. Not 16 though, 8 worked for me. Also, it must be stated that I had to deallocate the memory before. 

So if anyone else faces this, set the batch_size to lower values such as 8/16, and make sure the GPU is not occupied.

@hhaAndroid  thanks BTW.

**Comment by btekin** [comment]
With Pascal Titan X, a batch size of 32 works for me. Just make sure that you have enough memory by checking `(sudo) fuser -v /dev/nvidia*`. If you see some running processes deallocate memory by killing them.
