### ISSUE TITLE
Running out of memory during training

### ISSUE THREAD

**Issue by LukNeum** [Microsoft/singleshotpose#40]
First off, thanks for making your code available.

When running the training example I run into the following issue:
```
...
12808: nGT 32, recall 32, proposals 76, loss: x 0.398651, y 0.639343, conf 0.127928, total 1.165922
12834: nGT 26, recall 26, proposals 53, loss: x 0.760645, y 1.274382, conf 0.700860, total 2.735886
2018-09-12 17:44:04 epoch 69, processed 12834 samples, lr 0.001000
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1525796793591/work/torch/lib/THC/generic/THCStorage.cu line=58 error=2 : out of memory
Traceback (most recent call last):
  File "train.py", line 396, in <module>
    niter = train(epoch)
  File "train.py", line 86, in train
    output = model(data)
  File "/home/foo/miniconda2/envs/deeplearning/lib/python2.7/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/foo/projects/pose-detection/detectors/singleshotpose/darknet.py", line 91, in forward
    x = self.models[ind](x)
  File "/home/foo/miniconda2/envs/deeplearning/lib/python2.7/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/foo/miniconda2/envs/deeplearning/lib/python2.7/site-packages/torch/nn/modules/container.py", line 67, in forward
    input = module(input)
  File "/home/foo/miniconda2/envs/deeplearning/lib/python2.7/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/foo/miniconda2/envs/deeplearning/lib/python2.7/site-packages/torch/nn/modules/batchnorm.py", line 37, in forward
    self.training, self.momentum, self.eps)
  File "/home/foo/miniconda2/envs/deeplearning/lib/python2.7/site-packages/torch/nn/functional.py", line 1013, in batch_norm
    return f(input, weight, bias)
RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1525796793591/work/torch/lib/THC/generic/THCStorage.cu:58
```

How much memory is required for that particular example? I am using a GTX 1070 with 8Gb Memory with CUDA 8.0 and CUDNN 7.1.3, 8Gb RAM and PyTorch 0.3.1. Thanks.

**Comment by PeterZheFu** [comment]
This happened to me, too. I solved by changing the batch size from 32 to 16 in yolo-pose.cfg at https://github.com/Microsoft/singleshotpose/blob/1e6bfae97ee8e307abd3d06bf062b33f5d713af4/cfg/yolo-pose.cfg#L3

**Comment by btekin** [comment]
On Pascal TITAN X with 12 GB memory, there aren't any memory problems and the occupied space is around 8GB with a batch size of 32. The memory issue might be due to the multi-scale training. We change the input resolution during training randomly and with the increasing resolution of input images the activation maps are taking up more space. But still 8 GB of memory should be sufficient enough with a batch size of 16. Did you check if some other process is already running on GPU and taking up space. Just make sure that you have enough memory by checking (sudo) fuser -v /dev/nvidia*. If you see some running processes deallocate memory by killing them. Otherwise, you can further reduce the batch size. You might also find the discussion in #12 and #26 helpful to resolve your memory problem.

**Comment by LukNeum** [comment]
Turning down the batch size all the way to 8 did the trick, it appears to converge nicely anyway, thanks.
