### ISSUE TITLE
I got some problem when I use your project

### ISSUE THREAD

**Issue by superjiale** [Microsoft/singleshotpose#77]
hello，

I‘m sorry to disturb you. I'm a freshmen in this area, and I just want to run this in my own computer. But I got some problem when I try to run it. If you could help me, I would be very happy.
After I setup all these environment, it shows a error:

 31 detection
2019-04-04 17:20:45    Testing ape...
2019-04-04 17:20:45    Number of test samples: 1050
THCudaCheck FAIL file=/pytorch/torch/lib/THCUNN/generic/LeakyReLU.cu line=29 error=8 : invalid device function
Traceback (most recent call last):
.....
RuntimeError: cuda runtime error (8) : invalid device function at /pytorch/torch/lib/THCUNN/generic/LeakyReLU.cu:29

I just have no idea what happened. Should I change some parameters? I think maybe it is about computing power of my gpu. But I don't know what to do. Could you give me some advice? 
Feel most grateful!

[Ubuntu 16.04   GPU gtx950m  python 2.7  cuda 8.0  cudnn 5.1  pytorch 0.3.1]

**Comment by joefriel** [comment]
Maybe pytorch 0.3.1 does not support the 950M gpu?

See https://discuss.pytorch.org/t/pytorch-no-longer-supports-this-gpu-because-it-is-too-old/13803/2

**Comment by superjiale** [comment]
> Maybe pytorch 0.3.1 does not support the 950M gpu?
> 
> See https://discuss.pytorch.org/t/pytorch-no-longer-supports-this-gpu-because-it-is-too-old/13803/2



> Maybe pytorch 0.3.1 does not support the 950M gpu?
> 
> See https://discuss.pytorch.org/t/pytorch-no-longer-supports-this-gpu-because-it-is-too-old/13803/2

Yeah、I have seen that. But the problem is, when I change my pytorch, there will be another error about tensor, just like the #3 . However the solution of #3 couldn’t deal my problem perfectly.

**Comment by superjiale** [comment]
It is about the memory.
In the #12 hhaAndroid said that:

'irst: Num_worker is in utils.py，not in cfg
second:Batch is set in cfg
third：pytorch version must be 0.3，Can't be version 0.4'

So, I am confused... Does that means that this 'singleshotpose' only support for pytorch0.3?
If so, dose that means my computer would not run this anyway?

**Comment by btekin** [comment]
Hello, the implementation here is based on PyTorch 0.3.1 and tested on Python2.7. For a version that is Python 3 and Pytorch 0.4 compatible, you could see [this link](https://github.com/btekin/singleshot6Dpose), as also mentioned in the "Environment and Dependencies" section of the readme file. Hope this helps.

**Comment by joefriel** [comment]
I don't think moving to a later (higher) version of PyTorch is going to solve your problem, because they are also unlikely to support the 950 GPU (but I am not sure).

I think you have two options:

1) Compile PyTorch 3.1 from source (as described in the original PyTorch discussion I linked), or
2) Try PyTorch 3.0 (which looks like it may support your GPU, but of course singleshot is not tested against it)

I think compiling 3.1 from source is your best option.  Hope this helps.

Also, regarding the singleshot version mentioned by btekin (that supports Python 3 and PyTorch 0.4), it's great, I am successfully using it with PyTorch 1.0.  But I am not sure that is your easiest path.

**Comment by superjiale** [comment]
Thank you for all your reply! Github is such an amazing and friendly place!
And yes, after I changed my PyTorch-version to 0.4.1, it works!
So, I have solved this problem finally by these following steps. If you have the same problem, you can try these.

    1. I changed my python version from 2.7 to 3.7 
    2. Uninstall torch 0.3.1(seems PyTorch 0.3 no longer supports GTX 9xx, but supports GTX 10xx)
    3. Install torch 0.4.1.host2 and torchvision
        (It's IMPORTANT! It is **0.4.1.host2 instead of 0.4.1** !!  because when I used 0.4.1, there was runtime error about NumPy. but I don't know why)
    4. Use this project [https://github.com/btekin/singleshot6Dpose](url)
    5. Change batch from 32 to 16 ( for my memory is only 8G)
    6. Then, it works!

Special thanks to joefriel and btekin!
